[package]
name = "simple-rust-stack-interp"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]

[workspace]
members = [ "interp" ]

[[bin]]
name = "srsi"
path = "src/main.rs"

[dependencies]
interp = { path = "interp" }
